config/routes.rb
Rails.application.routes.draw do
  resources :messages, except: [:new]
  root 'messages#index'
end

app/models/message.rb
class Message < ActiveRecord::Base

  validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
    @message = Message.new
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
        format.js { render :create, status: :created}
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
        format.js { render :create, status: :created}
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
        format.js { render :update}
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
        format.js { render :update}
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
      format.js { render :destroy}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Rails Ajax"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="#" Rails Ajax
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= link_to "Link 1", "/path1"
            li= link_to "Link 2", "/path2"
            li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

      footer
        p &copy; Company 2015

app/views/layouts/modal.html.slim
#modal.bootstrap-modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="true"  ×
        h4.modal-title
          = content_for?(:title) ? yield(:title) : 'Modal'
      .modal-body
        = yield
      .modal-footer
        - if content_for?(:footer)
          yield(:footer)
        - else
          button.close aria-hidden="true" data-dismiss="true"  Close

app/views/messages/_form.html.slim
= form_for @message, html: { class: "form message" }, remote: true do |f|
  .form-group
    = f.label :body, :class => 'control-label'
    .controls
      = f.text_field :body, :class => 'form-control'
    = f.error_span(:body)
  = f.submit nil, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), messages_path, :class => 'btn'

app/views/messages/_message.html.slim
tr data-id="#{message.id}"
  td= link_to message.id, message_path(message)
  td= message.body
  td=l message.created_at
  td
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_message_path(message),
              remote: true, :class => 'btn btn-default btn-xs'
    '
    = link_to t('.destroy', :default => t("helpers.links.destroy")), message_path(message),
              :method => :delete, :class => 'btn btn-xs btn-danger', remote: true

app/views/messages/edit.html.slim
- model_class = Message
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/messages/index.html.slim
- model_class = Message
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:body)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @messages.each do |message|
      = render message
    tr
      td(colspan="4")= render partial: 'form'

app/views/messages/show.html.slim
- model_class = Message
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:body) + ':'
  br
  = @message.body

= link_to t('.back', :default => t("helpers.links.back")), messages_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_message_path(@message), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), message_path(@message), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'